
name: DevSecOps workflow

on:
  push:
    branches: [ "master" ]
  pull_request:
    # The branches below must be a subset of the branches above
    branches: [ "master" ]


permissions:
  contents: read
jobs:
  horusec-security:
      name: horusec-security
      runs-on: ubuntu-latest
      steps:
      - name: Check out code
        uses: actions/checkout@v2
        with: # Required when commit authors is enabled
          fetch-depth: 0
      - name: Running Horusec Security
        run: |
          curl -fsSL https://raw.githubusercontent.com/ZupIT/horusec/main/deployments/scripts/install.sh | bash -s latest
          horusec start --enable-commit-author  -j -p="./" -e="true" 
  build-secure-inmages:
      
      name: build-docker-images
      runs-on: ubuntu-latest
      steps:
      - name: Check out code
        uses: actions/checkout@v2
        with: # Required when commit authors is enabled
          fetch-depth: 0
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: goranpp/dvpa-secure:latest
          file: Dockerfile.app
      

       

       
